language: c

addons:
  apt:
    packages:
      - libpopt-dev

before_script:
  - ls -R `pwd`/deps
  - ./bootstrap

before_install:
  - bash install-deps.sh

install:
  - export PATH=$PATH:`pwd`/deps/bin
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:`pwd`/deps/lib/pkgconfig
  - export CFLAGS="$CFLAGS `pkg-config --cflags mondemand-4.0`"
  - export LIBS="$LIBS `pkg-config --libs mondemand-4.0`"
