language: c
before_script: ./bootstrap
install:
  - wget https://github.com/dukesoferl/fw/archive/rpm-0_9_2-noarch.tar.gz -O fw-0.9.2.tar.gz
  - tar -xzvf fw-0.9.2.tar.gz
  - cd fw-rpm-0_9_2-noarch && ./bootstrap && ./configure --prefix=$HOME && make && make install && cd ..
  - export PATH=$PATH:$HOME/bin
  - wget https://github.com/dukesoferl/fw-template-C/archive/rpm-0_0_11-noarch.tar.gz -O fw-template-C-0.0.11.tar.gz
  - tar -xzvf fw-template-C-0.0.11.tar.gz
  - cd fw-template-C-rpm-0_0_11-noarch && ./bootstrap && ./configure --prefix=$HOME && make && make install && cd ..
  - wget https://github.com/lwes/lwes/archive/lwes-0.24.0.tar.gz
  - tar -xzvf lwes-0.24.0.tar.gz
  - cd lwes-lwes-0.24.0 && ./bootstrap && ./configure --prefix=$HOME && make install && cd ..
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/lib/pkgconfig
  - export CFLAGS=$CFLAGS:`pkg-config --cflags lwes-0`
  - export LIBS=$LIBS:`pkg-config --libs lwes-0`
  - wget https://github.com/mondemand/mondemand/archive/rpm-4_2_1-x86_64.tar.gz -O mondemand-4.2.1.tar.gz
  - tar -xzvf mondemand-4.2.1.tar.gz
  - cd mondemand-rpm-4_2_1-x86_64 && ./bootstrap && ./configure --prefix=$HOME && make install && cd ..
  - export CFLAGS=$CFLAGS:`pkg-config --cflags mondemand-4.0`
  - export LIBS=$LIBS:`pkg-config --libs mondemand-4.0`
