#!/bin/sh

other=$*

cwd=`pwd`
rm -rf tmp
mkdir -p tmp
cd tmp
sudo ../lwes-journaller \
  --nodaemonize \
  -p 11311 \
  --pid-file $cwd/tmp/lwes-journaller.pid \
  --thread-type=process \
  --log-level=15 \
  --mondemand-host=centos65.local \
  --mondemand-ip=127.0.0.1 \
  --mondemand-port=20402 \
  -i 60 \
  -R \
  $other \
  $cwd/tmp/all_events.log.gz
