#!/bin/sh

other=$*

cwd=`pwd`
mkdir -p tmp
cd tmp
sudo ../lwes-journaller \
  --nodaemonize \
  -p 11311 \
  --pid-file $cwd/tmp/lwes-journaller.pid \
  --thread-type=process \
  --log-level=15 \
  -i 60 \
  -R \
  $other \
  $cwd/tmp/all_events.log.gz


#  -i 60 \
